package com.yunma.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.yunma.dao.AgentList;
import com.yunma.dao.AppInfo;
import com.yunma.dao.BrowsingHistory;
import com.yunma.dao.ConsigneeAddress;
import com.yunma.dao.ContactsInfos;
import com.yunma.dao.GoodsBrands;
import com.yunma.dao.GoodsSize;
import com.yunma.dao.GoodsType;
import com.yunma.dao.HistroySearch;
import com.yunma.dao.SystemNotices;
import com.yunma.dao.UserInfos;

import com.yunma.greendao.AgentListDao;
import com.yunma.greendao.AppInfoDao;
import com.yunma.greendao.BrowsingHistoryDao;
import com.yunma.greendao.ConsigneeAddressDao;
import com.yunma.greendao.ContactsInfosDao;
import com.yunma.greendao.GoodsBrandsDao;
import com.yunma.greendao.GoodsSizeDao;
import com.yunma.greendao.GoodsTypeDao;
import com.yunma.greendao.HistroySearchDao;
import com.yunma.greendao.SystemNoticesDao;
import com.yunma.greendao.UserInfosDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig agentListDaoConfig;
    private final DaoConfig appInfoDaoConfig;
    private final DaoConfig browsingHistoryDaoConfig;
    private final DaoConfig consigneeAddressDaoConfig;
    private final DaoConfig contactsInfosDaoConfig;
    private final DaoConfig goodsBrandsDaoConfig;
    private final DaoConfig goodsSizeDaoConfig;
    private final DaoConfig goodsTypeDaoConfig;
    private final DaoConfig histroySearchDaoConfig;
    private final DaoConfig systemNoticesDaoConfig;
    private final DaoConfig userInfosDaoConfig;

    private final AgentListDao agentListDao;
    private final AppInfoDao appInfoDao;
    private final BrowsingHistoryDao browsingHistoryDao;
    private final ConsigneeAddressDao consigneeAddressDao;
    private final ContactsInfosDao contactsInfosDao;
    private final GoodsBrandsDao goodsBrandsDao;
    private final GoodsSizeDao goodsSizeDao;
    private final GoodsTypeDao goodsTypeDao;
    private final HistroySearchDao histroySearchDao;
    private final SystemNoticesDao systemNoticesDao;
    private final UserInfosDao userInfosDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        agentListDaoConfig = daoConfigMap.get(AgentListDao.class).clone();
        agentListDaoConfig.initIdentityScope(type);

        appInfoDaoConfig = daoConfigMap.get(AppInfoDao.class).clone();
        appInfoDaoConfig.initIdentityScope(type);

        browsingHistoryDaoConfig = daoConfigMap.get(BrowsingHistoryDao.class).clone();
        browsingHistoryDaoConfig.initIdentityScope(type);

        consigneeAddressDaoConfig = daoConfigMap.get(ConsigneeAddressDao.class).clone();
        consigneeAddressDaoConfig.initIdentityScope(type);

        contactsInfosDaoConfig = daoConfigMap.get(ContactsInfosDao.class).clone();
        contactsInfosDaoConfig.initIdentityScope(type);

        goodsBrandsDaoConfig = daoConfigMap.get(GoodsBrandsDao.class).clone();
        goodsBrandsDaoConfig.initIdentityScope(type);

        goodsSizeDaoConfig = daoConfigMap.get(GoodsSizeDao.class).clone();
        goodsSizeDaoConfig.initIdentityScope(type);

        goodsTypeDaoConfig = daoConfigMap.get(GoodsTypeDao.class).clone();
        goodsTypeDaoConfig.initIdentityScope(type);

        histroySearchDaoConfig = daoConfigMap.get(HistroySearchDao.class).clone();
        histroySearchDaoConfig.initIdentityScope(type);

        systemNoticesDaoConfig = daoConfigMap.get(SystemNoticesDao.class).clone();
        systemNoticesDaoConfig.initIdentityScope(type);

        userInfosDaoConfig = daoConfigMap.get(UserInfosDao.class).clone();
        userInfosDaoConfig.initIdentityScope(type);

        agentListDao = new AgentListDao(agentListDaoConfig, this);
        appInfoDao = new AppInfoDao(appInfoDaoConfig, this);
        browsingHistoryDao = new BrowsingHistoryDao(browsingHistoryDaoConfig, this);
        consigneeAddressDao = new ConsigneeAddressDao(consigneeAddressDaoConfig, this);
        contactsInfosDao = new ContactsInfosDao(contactsInfosDaoConfig, this);
        goodsBrandsDao = new GoodsBrandsDao(goodsBrandsDaoConfig, this);
        goodsSizeDao = new GoodsSizeDao(goodsSizeDaoConfig, this);
        goodsTypeDao = new GoodsTypeDao(goodsTypeDaoConfig, this);
        histroySearchDao = new HistroySearchDao(histroySearchDaoConfig, this);
        systemNoticesDao = new SystemNoticesDao(systemNoticesDaoConfig, this);
        userInfosDao = new UserInfosDao(userInfosDaoConfig, this);

        registerDao(AgentList.class, agentListDao);
        registerDao(AppInfo.class, appInfoDao);
        registerDao(BrowsingHistory.class, browsingHistoryDao);
        registerDao(ConsigneeAddress.class, consigneeAddressDao);
        registerDao(ContactsInfos.class, contactsInfosDao);
        registerDao(GoodsBrands.class, goodsBrandsDao);
        registerDao(GoodsSize.class, goodsSizeDao);
        registerDao(GoodsType.class, goodsTypeDao);
        registerDao(HistroySearch.class, histroySearchDao);
        registerDao(SystemNotices.class, systemNoticesDao);
        registerDao(UserInfos.class, userInfosDao);
    }
    
    public void clear() {
        agentListDaoConfig.clearIdentityScope();
        appInfoDaoConfig.clearIdentityScope();
        browsingHistoryDaoConfig.clearIdentityScope();
        consigneeAddressDaoConfig.clearIdentityScope();
        contactsInfosDaoConfig.clearIdentityScope();
        goodsBrandsDaoConfig.clearIdentityScope();
        goodsSizeDaoConfig.clearIdentityScope();
        goodsTypeDaoConfig.clearIdentityScope();
        histroySearchDaoConfig.clearIdentityScope();
        systemNoticesDaoConfig.clearIdentityScope();
        userInfosDaoConfig.clearIdentityScope();
    }

    public AgentListDao getAgentListDao() {
        return agentListDao;
    }

    public AppInfoDao getAppInfoDao() {
        return appInfoDao;
    }

    public BrowsingHistoryDao getBrowsingHistoryDao() {
        return browsingHistoryDao;
    }

    public ConsigneeAddressDao getConsigneeAddressDao() {
        return consigneeAddressDao;
    }

    public ContactsInfosDao getContactsInfosDao() {
        return contactsInfosDao;
    }

    public GoodsBrandsDao getGoodsBrandsDao() {
        return goodsBrandsDao;
    }

    public GoodsSizeDao getGoodsSizeDao() {
        return goodsSizeDao;
    }

    public GoodsTypeDao getGoodsTypeDao() {
        return goodsTypeDao;
    }

    public HistroySearchDao getHistroySearchDao() {
        return histroySearchDao;
    }

    public SystemNoticesDao getSystemNoticesDao() {
        return systemNoticesDao;
    }

    public UserInfosDao getUserInfosDao() {
        return userInfosDao;
    }

}
