package com.yunma.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.yunma.dao.AppInfo;
import com.yunma.dao.HistroySearch;
import com.yunma.dao.UserInfos;

import com.yunma.greendao.AppInfoDao;
import com.yunma.greendao.HistroySearchDao;
import com.yunma.greendao.UserInfosDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig appInfoDaoConfig;
    private final DaoConfig histroySearchDaoConfig;
    private final DaoConfig userInfosDaoConfig;

    private final AppInfoDao appInfoDao;
    private final HistroySearchDao histroySearchDao;
    private final UserInfosDao userInfosDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        appInfoDaoConfig = daoConfigMap.get(AppInfoDao.class).clone();
        appInfoDaoConfig.initIdentityScope(type);

        histroySearchDaoConfig = daoConfigMap.get(HistroySearchDao.class).clone();
        histroySearchDaoConfig.initIdentityScope(type);

        userInfosDaoConfig = daoConfigMap.get(UserInfosDao.class).clone();
        userInfosDaoConfig.initIdentityScope(type);

        appInfoDao = new AppInfoDao(appInfoDaoConfig, this);
        histroySearchDao = new HistroySearchDao(histroySearchDaoConfig, this);
        userInfosDao = new UserInfosDao(userInfosDaoConfig, this);

        registerDao(AppInfo.class, appInfoDao);
        registerDao(HistroySearch.class, histroySearchDao);
        registerDao(UserInfos.class, userInfosDao);
    }
    
    public void clear() {
        appInfoDaoConfig.clearIdentityScope();
        histroySearchDaoConfig.clearIdentityScope();
        userInfosDaoConfig.clearIdentityScope();
    }

    public AppInfoDao getAppInfoDao() {
        return appInfoDao;
    }

    public HistroySearchDao getHistroySearchDao() {
        return histroySearchDao;
    }

    public UserInfosDao getUserInfosDao() {
        return userInfosDao;
    }

}
